Vrms = input('RMS Voltage = ');
Irms = input('RMS Current = ');
P.F = input('Power Factor = ');
theta = acosd(P.F);
wt = 0:.05:2*pi;
% wt = 180/pi*wt;
xline = zeros(1, length(wt));
Vt = Vrms*sin(wt);
It = Irms*sin(wt-theta);
Pt = Vt .* It;
plot(wt,Vt, wt,It, wt,xline), grid('on');